# INTRODUCCI칍N


Las remesas son transferencias de dinero realizadas principalmente por emigrantes a sus familiares o relacionados en su pa칤s de origen. En este proceso participan los siguientes actores: remitente (persona que desde el pa칤s de origen se acerca a un agente para enviar un determinado monto), el agente en el lugar de origen (oficina donde se inicia la operaci칩n financiera), la empresa de transferencia de dinero (empresa que hace el traslado del monto del pa칤s de origen al pa칤s destino), el agente en el lugar de pago (oficina donde se realiza el desembolso del dinero) y el receptor (persona que en el pa칤s de destino recibe el dinero). Las transferencias entre la empresa de transferencia y los agentes se realizan en d칩lares, y las tasas de cambio se fijan en la fecha de origen de la transacci칩n con una tasa de referencia establecida para cada pa칤s. Esto significa que todas las transacciones
iniciadas en el d칤a 洧노 se pagar치n seg칰n la tasa de referencia correspondiente a ese d칤a.

Esto genera un desaf칤o para los agentes en el lugar de pago, dado que la tasa de pago asociada a las operaciones es informada al remitente y se fija seg칰n la tasa de referencia vigente en la fecha de origen y se mantiene inalterada hasta que el giro es cobrado. Existe una exposici칩n a la volatilidad de la tasa de cambio entre el d칤a inicial de la transacci칩n
y la fecha de cobro.

Estas transacciones se identifican el d칤a en que se realiza el pago al receptor, momento en que la tasa de mercado a la que el agente de pago convierte a moneda local los d칩lares recibidos por la empresa de transferencia de dinero puede haber variado con relaci칩n a la tasa de cambio con la que se fij칩 la conversi칩n al momento de la originaci칩n de la remesa.

En resumen, hay transacciones pagadas en el d칤a 洧노 que tienen como referencia una tasa de cambio de un d칤a diferente, y el agente del lugar de pago puede monetizar (convertir de d칩lares a pesos colombianos) a la tasa del d칤a 洧노. De esta forma, en escenarios de revaluaci칩n del peso colombiano, es decir, ca칤das en la tasa de cambio, se generar칤an menores ingresos o p칠rdidas por concepto de monetizaci칩n de d칩lares, materializ치ndose el riesgo cambiario. Este proceso se ve afectado por las celebraciones especiales en cada uno de los pa칤ses, tales como d칤a de amor y amistad, d칤a de la madre, navidad, etc.

## BASE DE DATOS

Seg칰n lo expuesto anteriormente, se identifican las siguientes variables para el conjunto de datos provisto por una entidad que realiza remesas en Colombia bajo acuerdo de confidencialidad:

+:------------------------+:--------------------------------+
| -   **Fecha de pago.**  | -   **Canal.**                  |
+-------------------------+---------------------------------+
| -   **Pais de Origen.** | -   **N칰mero de                 |
|                         |     transacciones.**            |
+-------------------------+---------------------------------+
| -   **Fecha de          | -   **Monto en dolares.**       |
|     origen.**           |                                 |
+-------------------------+---------------------------------+
| -   **Monto en Pesos.** |                                 |
+-------------------------+---------------------------------+

En relaci칩n con la importancia de analizar esta informaci칩n enfocado en la variable tiempo se puede decir que; el an치lisis de las variables de tipo fecha (Fecha origen de la operaci칩n y Fecha de pago) es crucial debido a la volatilidad de las tasas de cambio entre el d칤a en que se origina la remesa y el d칤a en que se paga. Por otra parte, el pron칩stico del monto
total a pagar en remesas es esencial para mitigar este riesgo, permitiendo anticipar posibles p칠rdidas por variaciones en la tasa de cambio y tomar decisiones informadas sobre cobertura y gesti칩n del riesgo.

Inicialmente los datos comprenden el periodo entre el primero de enero de 2023 hasta el 10 de octubre de 2024 de forma d칤aria, pero se ir치 aumentando los datos en la medida que la empresa entregue la informaci칩n.

