<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 HOLT - WINTERS | Series de tiempo - Remesas</title>
  <meta name="description" content="4 HOLT - WINTERS | Series de tiempo - Remesas" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="4 HOLT - WINTERS | Series de tiempo - Remesas" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 HOLT - WINTERS | Series de tiempo - Remesas" />
  
  
  

<meta name="author" content="Analisis de Series de Tiempo Grupo 5 - William Contreras, Camilo Espinoza, Jorge Agredo" />


<meta name="date" content="2024-11-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preprocesamiento-y-visualizacion.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="remesas.html"><a href="remesas.html"><i class="fa fa-check"></i><b>1</b> REMESAS</a>
<ul>
<li class="chapter" data-level="1.1" data-path="remesas.html"><a href="remesas.html#introducción"><i class="fa fa-check"></i><b>1.1</b> INTRODUCCIÓN</a></li>
<li class="chapter" data-level="1.2" data-path="remesas.html"><a href="remesas.html#base-de-datos"><i class="fa fa-check"></i><b>1.2</b> BASE DE DATOS</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> DESCRIPCIÓN DE LAS SERIES DE TIEMPO</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>2.1</b> Serie de tiempo por Fecha de Pago</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts"><i class="fa fa-check"></i><b>2.1.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.1.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo"><i class="fa fa-check"></i><b>2.1.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.1.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles"><i class="fa fa-check"></i><b>2.1.3</b> Promedios móviles</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-origen"><i class="fa fa-check"></i><b>2.2</b> Serie de tiempo por Fecha de Origen</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts-1"><i class="fa fa-check"></i><b>2.2.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo-1"><i class="fa fa-check"></i><b>2.2.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.2.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles-1"><i class="fa fa-check"></i><b>2.2.3</b> Promedios móviles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html"><i class="fa fa-check"></i><b>3</b> PREPROCESAMIENTO Y VISUALIZACION</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#descomposición-de-la-serie-temporal---serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>3.1</b> Descomposición de la serie temporal - Serie de tiempo por Fecha de Pago</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#estacionariedad"><i class="fa fa-check"></i><b>3.1.1</b> Estacionariedad</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#función-de-autocorrelación-acf-y-función-de-autocorrelación-parcial-pacf"><i class="fa fa-check"></i><b>3.2</b> Función de Autocorrelación (ACF) y Función de Autocorrelación Parcial (PACF)</a></li>
<li class="chapter" data-level="3.3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#componentes-de-la-descomposición"><i class="fa fa-check"></i><b>3.3</b> Componentes de la Descomposición</a></li>
<li class="chapter" data-level="3.4" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#modelo-arima"><i class="fa fa-check"></i><b>3.4</b> Modelo ARIMA</a></li>
<li class="chapter" data-level="3.5" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#punto-de-cambio-de-la-serie-de-tiempo"><i class="fa fa-check"></i><b>3.5</b> Punto de cambio de la serie de tiempo</a></li>
<li class="chapter" data-level="3.6" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#predicciones-del-modelo-arima"><i class="fa fa-check"></i><b>3.6</b> Predicciones del Modelo ARIMA</a></li>
<li class="chapter" data-level="3.7" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#validaciones"><i class="fa fa-check"></i><b>3.7</b> Validaciones</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#outliers"><i class="fa fa-check"></i><b>3.7.1</b> Outliers</a></li>
<li class="chapter" data-level="3.7.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#supuestos-de-una-arima"><i class="fa fa-check"></i><b>3.7.2</b> Supuestos de una ARIMA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="holt---winters.html"><a href="holt---winters.html"><i class="fa fa-check"></i><b>4</b> HOLT - WINTERS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="holt---winters.html"><a href="holt---winters.html#visualizacion-de-la-variación-de-los-pagos-a-lo-largo-del-tiempo"><i class="fa fa-check"></i><b>4.1</b> Visualizacion de la variación de los pagos a lo largo del tiempo</a></li>
<li class="chapter" data-level="4.2" data-path="holt---winters.html"><a href="holt---winters.html#definición-y-caracteristicas-de-la-serie."><i class="fa fa-check"></i><b>4.2</b> Definición y caracteristicas de la serie.</a></li>
<li class="chapter" data-level="4.3" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-de-caja-boxplot-por-día-de-la-semana"><i class="fa fa-check"></i><b>4.3</b> Gráfico de Caja (Boxplot) por Día de la Semana</a></li>
<li class="chapter" data-level="4.4" data-path="holt---winters.html"><a href="holt---winters.html#logaritmo-de-monto-en-dolares"><i class="fa fa-check"></i><b>4.4</b> Logaritmo de Monto en Dolares</a></li>
<li class="chapter" data-level="4.5" data-path="holt---winters.html"><a href="holt---winters.html#aplicacion-del-modelo-holt-winter"><i class="fa fa-check"></i><b>4.5</b> Aplicacion del modelo Holt-Winter</a></li>
<li class="chapter" data-level="4.6" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-del-ajuste-del-modelo-de-holt-winters"><i class="fa fa-check"></i><b>4.6</b> Gráfico del Ajuste del Modelo de Holt-Winters</a></li>
<li class="chapter" data-level="4.7" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-de-la-descomposición-de-holt-winters"><i class="fa fa-check"></i><b>4.7</b> Gráfico de la Descomposición de Holt-Winters</a></li>
<li class="chapter" data-level="4.8" data-path="holt---winters.html"><a href="holt---winters.html#predicciones-a-partir-del-modelo-de-holt-winters"><i class="fa fa-check"></i><b>4.8</b> Predicciones a partir del modelo de Holt-Winters</a></li>
<li class="chapter" data-level="4.9" data-path="holt---winters.html"><a href="holt---winters.html#funcion-exponencial-para-regresar-a-la-escala-original."><i class="fa fa-check"></i><b>4.9</b> Funcion exponencial para regresar a la escala original.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de tiempo - Remesas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="holt---winters" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> HOLT - WINTERS<a href="holt---winters.html#holt---winters" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<pre><code>##   Fecha_Pago Monto_USD
## 1 2023-01-01  314473.1
## 2 2023-01-02 4700346.1
## 3 2023-01-03 6069974.1
## 4 2023-01-04 6164948.9
## 5 2023-01-05 6986643.0
## 6 2023-01-06 6616416.0</code></pre>
<div id="visualizacion-de-la-variación-de-los-pagos-a-lo-largo-del-tiempo" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Visualizacion de la variación de los pagos a lo largo del tiempo<a href="holt---winters.html#visualizacion-de-la-variación-de-los-pagos-a-lo-largo-del-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
</div>
<div id="definición-y-caracteristicas-de-la-serie." class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Definición y caracteristicas de la serie.<a href="holt---winters.html#definición-y-caracteristicas-de-la-serie." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## Time Series:
## Start = c(2023, 1) 
## End = c(2023, 20) 
## Frequency = 365 
##  [1]  314473.1 4700346.1 6069974.1 6164948.9 6986643.0 6616416.0 5392530.2 1368008.4 2248875.5
## [10] 8307518.8 6546327.3 4509599.3 5737621.1 4668733.8 1329182.5 6681862.6 5926830.6 5664752.1
## [19] 5235327.5 5645884.9</code></pre>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
##   314473  5732341  7045531  6592872  8074062 13866707</code></pre>
<p>La serie de tiempo <code>Datos_FP_ts</code> muestra el comportamiento de los montos de pago en dólares registrados diariamente desde enero de 2023.</p>
<ul>
<li><strong>Valor mínimo (Min)</strong>: El monto más bajo registrado es de <strong>314,473 USD</strong>.</li>
<li><strong>Primer cuartil (1st Qu.)</strong>: El 25% de los montos registrados son menores o iguales a <strong>5,732,341 USD</strong>.</li>
<li><strong>Mediana (Median)</strong>: El valor central de la serie es <strong>7,045,531 USD</strong>, lo que indica que la mitad de los montos son mayores o iguales a este valor y la otra mitad son menores.</li>
<li><strong>Media (Mean)</strong>: El promedio de los montos es de <strong>6,592,872 USD</strong>, lo cual está relativamente cerca de la mediana, sugiriendo que no hay una gran asimetría en los datos.</li>
<li><strong>Tercer cuartil (3rd Qu.)</strong>: El 75% de los montos son menores o iguales a <strong>8,074,062 USD</strong>.</li>
<li><strong>Valor máximo (Max)</strong>: El monto máximo registrado es de <strong>13,866,707 USD</strong>.</li>
</ul>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
</div>
<div id="gráfico-de-caja-boxplot-por-día-de-la-semana" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Gráfico de Caja (Boxplot) por Día de la Semana<a href="holt---winters.html#gráfico-de-caja-boxplot-por-día-de-la-semana" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>El gráfico de cajas muestra la distribución de los montos en dólares (Monto_USD) para cada día de la semana (Dia_semana). El es comparar los montos de pago en función del día de la semana para identificar variaciones, como si ciertos días tienden a tener pagos más altos o más bajos.</p>
<p>En este caso, es notable que el dia domingo se registran valores mas bajos en comparación con los demas dias de la semana.</p>
</div>
<div id="logaritmo-de-monto-en-dolares" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Logaritmo de Monto en Dolares<a href="holt---winters.html#logaritmo-de-monto-en-dolares" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El siguiente grafico permite visualizar la evolución de los pagos en el tiempo, facilitando la observación de cambios y patrones en la serie al suavizar la variabilidad de los datos.</p>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
</div>
<div id="aplicacion-del-modelo-holt-winter" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Aplicacion del modelo Holt-Winter<a href="holt---winters.html#aplicacion-del-modelo-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación se utiliza una serie de tiempo transformada a escala logarítmica para aplicar el modelo de Holt-Winters para ajustar y descomponer la serie.</p>
<p>Se aplica el modelo de Holt-Winters con un componente estacional aditivo (seasonal = “additive”) a la serie Datos_FP_ts2. El modelo de Holt-Winters es un método de suavizamiento exponencial que se utiliza para ajustar y pronosticar series de tiempo con componentes estacionales, tendencia y aleatoriedad.</p>
<p><strong>Estacionalidad aditiva:</strong> Se asume que los efectos estacionales son constantes y no dependen del nivel de la serie.</p>
</div>
<div id="gráfico-del-ajuste-del-modelo-de-holt-winters" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Gráfico del Ajuste del Modelo de Holt-Winters<a href="holt---winters.html#gráfico-del-ajuste-del-modelo-de-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
</div>
<div id="gráfico-de-la-descomposición-de-holt-winters" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Gráfico de la Descomposición de Holt-Winters<a href="holt---winters.html#gráfico-de-la-descomposición-de-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
</div>
<div id="predicciones-a-partir-del-modelo-de-holt-winters" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> Predicciones a partir del modelo de Holt-Winters<a href="holt---winters.html#predicciones-a-partir-del-modelo-de-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## Time Series:
## Start = c(2115, 6) 
## End = c(2117, 5) 
## Frequency = 7 
##               fit      upr      lwr
## 2115.714 16.11265 16.67574 15.54956
## 2115.857 15.88687 16.45135 15.32240
## 2116.000 14.82100 15.38687 14.25512
## 2116.143 16.06591 16.63320 15.49862
## 2116.286 16.14283 16.71154 15.57411
## 2116.429 16.04821 16.61837 15.47805
## 2116.571 16.03847 16.61008 15.46686
## 2116.714 16.11836 16.70473 15.53200
## 2116.857 15.89259 16.48040 15.30478
## 2117.000 14.82671 15.41599 14.23744
## 2117.143 16.07162 16.66238 15.48087
## 2117.286 16.14854 16.74079 15.55629
## 2117.429 16.05392 16.64768 15.46017
## 2117.571 16.04418 16.63946 15.44891</code></pre>
<p>La tabla muestra cómo el modelo de Holt-Winters estima las fluctuaciones diarias del monto en dólares en los próximos 14 días, reflejando una variabilidad ligera. Los intervalos ayudan a interpretar la predicción en función de su incertidumbre, lo que es clave para evaluar posibles escenarios en los valores futuros de los pagos.</p>
</div>
<div id="funcion-exponencial-para-regresar-a-la-escala-original." class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> Funcion exponencial para regresar a la escala original.<a href="holt---winters.html#funcion-exponencial-para-regresar-a-la-escala-original." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>##         fit      upr     lwr
## 1   9945695 17465553 5663540
## 2   7935638 13955019 4512667
## 3   2733240  4813200 1552107
## 4   9491504 16738052 5382266
## 5  10250405 18102176 5804319
## 6   9325010 16491689 5272706
## 7   9234597 16355581 5213987
## 8  10002685 17979182 5564976
## 9   7981110 14366357 4433840
## 10  2748902  4955400 1524895
## 11  9545892 17233686 5287554
## 12 10309141 18639424 5701807
## 13  9378444 16982250 5179244
## 14  9287513 16843192 5121232</code></pre>
<p>Esta salida muestra las predicciones y los intervalos de confianza de un modelo de serie de tiempo para el monto en dólares. Cada fila representa un día.</p>
<p><strong><code>fit</code></strong>: Valor predicho central en dólares. Es el valor estimado para el monto en este periodo.
<strong><code>upr</code></strong>: Límite superior del intervalo de predicción en dólares. Representa el valor máximo esperado en ese intervalo, proporcionando un margen de incertidumbre hacia arriba.
<strong><code>lwr</code></strong>: Límite inferior del intervalo de predicción en dólares. Indica el valor mínimo esperado, estableciendo el margen de incertidumbre hacia abajo.</p>
<p>Este intervalo entre <code>upr</code> y <code>lwr</code> ayuda a entender la variabilidad y la confiabilidad de la predicción en cada periodo.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preprocesamiento-y-visualizacion.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/4_Holter-Winter.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Remesas en dolares.pdf", "Remesas en dolares.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
