<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 MODELOS ESTACIONARIOS | Series de tiempo - Remesas</title>
  <meta name="description" content="5 MODELOS ESTACIONARIOS | Series de tiempo - Remesas" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="5 MODELOS ESTACIONARIOS | Series de tiempo - Remesas" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 MODELOS ESTACIONARIOS | Series de tiempo - Remesas" />
  
  
  

<meta name="author" content="Analisis de Series de Tiempo Grupo 5 - William Contreras, Camilo Espinoza, Jorge Agredo" />


<meta name="date" content="2024-11-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="holt---winters.html"/>
<link rel="next" href="modelo-prophet.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="remesas.html"><a href="remesas.html"><i class="fa fa-check"></i><b>1</b> REMESAS</a>
<ul>
<li class="chapter" data-level="1.1" data-path="remesas.html"><a href="remesas.html#introducción"><i class="fa fa-check"></i><b>1.1</b> INTRODUCCIÓN</a></li>
<li class="chapter" data-level="1.2" data-path="remesas.html"><a href="remesas.html#base-de-datos"><i class="fa fa-check"></i><b>1.2</b> BASE DE DATOS</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> DESCRIPCIÓN DE LAS SERIES DE TIEMPO</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>2.1</b> Serie de tiempo por Fecha de Pago</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts"><i class="fa fa-check"></i><b>2.1.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.1.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo"><i class="fa fa-check"></i><b>2.1.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.1.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles"><i class="fa fa-check"></i><b>2.1.3</b> Promedios móviles</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-origen"><i class="fa fa-check"></i><b>2.2</b> Serie de tiempo por Fecha de Origen</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts-1"><i class="fa fa-check"></i><b>2.2.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo-1"><i class="fa fa-check"></i><b>2.2.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.2.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles-1"><i class="fa fa-check"></i><b>2.2.3</b> Promedios móviles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html"><i class="fa fa-check"></i><b>3</b> PREPROCESAMIENTO Y VISUALIZACION</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#descomposición-de-la-serie-temporal---serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>3.1</b> Descomposición de la serie temporal - Serie de tiempo por Fecha de Pago</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#estacionariedad"><i class="fa fa-check"></i><b>3.1.1</b> Estacionariedad</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#función-de-autocorrelación-acf-y-función-de-autocorrelación-parcial-pacf"><i class="fa fa-check"></i><b>3.2</b> Función de Autocorrelación (ACF) y Función de Autocorrelación Parcial (PACF)</a></li>
<li class="chapter" data-level="3.3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#componentes-de-la-descomposición"><i class="fa fa-check"></i><b>3.3</b> Componentes de la Descomposición</a></li>
<li class="chapter" data-level="3.4" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#modelo-arima"><i class="fa fa-check"></i><b>3.4</b> Modelo ARIMA</a></li>
<li class="chapter" data-level="3.5" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#punto-de-cambio-de-la-serie-de-tiempo"><i class="fa fa-check"></i><b>3.5</b> Punto de cambio de la serie de tiempo</a></li>
<li class="chapter" data-level="3.6" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#predicciones-del-modelo-arima"><i class="fa fa-check"></i><b>3.6</b> Predicciones del Modelo ARIMA</a></li>
<li class="chapter" data-level="3.7" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#validaciones"><i class="fa fa-check"></i><b>3.7</b> Validaciones</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#outliers"><i class="fa fa-check"></i><b>3.7.1</b> Outliers</a></li>
<li class="chapter" data-level="3.7.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#supuestos-de-una-arima"><i class="fa fa-check"></i><b>3.7.2</b> Supuestos de una ARIMA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="holt---winters.html"><a href="holt---winters.html"><i class="fa fa-check"></i><b>4</b> HOLT - WINTERS</a>
<ul>
<li class="chapter" data-level="4.1" data-path="holt---winters.html"><a href="holt---winters.html#visualizacion-de-la-variación-de-los-pagos-a-lo-largo-del-tiempo"><i class="fa fa-check"></i><b>4.1</b> Visualizacion de la variación de los pagos a lo largo del tiempo</a></li>
<li class="chapter" data-level="4.2" data-path="holt---winters.html"><a href="holt---winters.html#definición-y-caracteristicas-de-la-serie."><i class="fa fa-check"></i><b>4.2</b> Definición y caracteristicas de la serie.</a></li>
<li class="chapter" data-level="4.3" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-de-caja-boxplot-por-día-de-la-semana"><i class="fa fa-check"></i><b>4.3</b> Gráfico de Caja (Boxplot) por Día de la Semana</a></li>
<li class="chapter" data-level="4.4" data-path="holt---winters.html"><a href="holt---winters.html#logaritmo-de-monto-en-dolares"><i class="fa fa-check"></i><b>4.4</b> Logaritmo de Monto en Dolares</a></li>
<li class="chapter" data-level="4.5" data-path="holt---winters.html"><a href="holt---winters.html#aplicacion-del-modelo-holt-winter"><i class="fa fa-check"></i><b>4.5</b> Aplicacion del modelo Holt-Winter</a></li>
<li class="chapter" data-level="4.6" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-del-ajuste-del-modelo-de-holt-winters"><i class="fa fa-check"></i><b>4.6</b> Gráfico del Ajuste del Modelo de Holt-Winters</a></li>
<li class="chapter" data-level="4.7" data-path="holt---winters.html"><a href="holt---winters.html#gráfico-de-la-descomposición-de-holt-winters"><i class="fa fa-check"></i><b>4.7</b> Gráfico de la Descomposición de Holt-Winters</a></li>
<li class="chapter" data-level="4.8" data-path="holt---winters.html"><a href="holt---winters.html#predicciones-a-partir-del-modelo-de-holt-winters"><i class="fa fa-check"></i><b>4.8</b> Predicciones a partir del modelo de Holt-Winters</a></li>
<li class="chapter" data-level="4.9" data-path="holt---winters.html"><a href="holt---winters.html#funcion-exponencial-para-regresar-a-la-escala-original."><i class="fa fa-check"></i><b>4.9</b> Funcion exponencial para regresar a la escala original.</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html"><i class="fa fa-check"></i><b>5</b> MODELOS ESTACIONARIOS</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#metodología-box-jenkins"><i class="fa fa-check"></i><b>5.1</b> METODOLOGÍA BOX-JENKINS</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#visualizacion-de-la-serie"><i class="fa fa-check"></i><b>5.1.1</b> Visualizacion de la serie</a></li>
<li class="chapter" data-level="5.1.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#verificación-de-estacionariedad"><i class="fa fa-check"></i><b>5.1.2</b> Verificación de estacionariedad</a></li>
<li class="chapter" data-level="5.1.3" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#análisis-acf-y-pacf"><i class="fa fa-check"></i><b>5.1.3</b> Análisis ACF y PACF</a></li>
<li class="chapter" data-level="5.1.4" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#ajuste-del-modelo"><i class="fa fa-check"></i><b>5.1.4</b> Ajuste del modelo</a></li>
<li class="chapter" data-level="5.1.5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#pronóstico"><i class="fa fa-check"></i><b>5.1.5</b> Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#inclución-de-variables-en-el-tiempo-y-ajustes-a-un-modelo-lineal-y-estacionario"><i class="fa fa-check"></i><b>5.2</b> INCLUCIÓN DE VARIABLES EN EL TIEMPO Y AJUSTES A UN MODELO LINEAL Y ESTACIONARIO</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#creación-de-variables-temporales-a-partir-de-la-fecha-de-pago"><i class="fa fa-check"></i><b>5.2.1</b> Creación de variables temporales a partir de la fecha de pago</a></li>
<li class="chapter" data-level="5.2.2" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#verificacion-de-la-misma-cobertura-de-fechas-de-las-dos-fuentes."><i class="fa fa-check"></i><b>5.2.2</b> Verificacion de la misma cobertura de fechas de las dos fuentes.</a></li>
<li class="chapter" data-level="5.2.3" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#agregar-las-variables-al-índice-de-la-serie"><i class="fa fa-check"></i><b>5.2.3</b> Agregar las variables al índice de la serie</a></li>
<li class="chapter" data-level="5.2.4" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#unión-de-las-variables-adicionales"><i class="fa fa-check"></i><b>5.2.4</b> Unión de las variables adicionales</a></li>
<li class="chapter" data-level="5.2.5" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#preparar"><i class="fa fa-check"></i><b>5.2.5</b> Preparar</a></li>
<li class="chapter" data-level="5.2.6" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#ajuste-del-modelo-arimax-con-los-datos-combinados-y-xreg."><i class="fa fa-check"></i><b>5.2.6</b> Ajuste del modelo ARIMAX Con los datos combinados y xreg.</a></li>
<li class="chapter" data-level="5.2.7" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#resumen-de-los-coeficientes"><i class="fa fa-check"></i><b>5.2.7</b> <strong>Resumen de los Coeficientes:</strong></a></li>
<li class="chapter" data-level="5.2.8" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#métricas-del-modelo"><i class="fa fa-check"></i><b>5.2.8</b> <strong>Métricas del Modelo:</strong></a></li>
<li class="chapter" data-level="5.2.9" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#errores-en-el-conjunto-de-entrenamiento"><i class="fa fa-check"></i><b>5.2.9</b> <strong>Errores en el conjunto de entrenamiento:</strong></a></li>
<li class="chapter" data-level="5.2.10" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#validación"><i class="fa fa-check"></i><b>5.2.10</b> Validación</a></li>
<li class="chapter" data-level="5.2.11" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#ljung-box-test"><i class="fa fa-check"></i><b>5.2.11</b> <strong>Ljung-Box test:</strong></a></li>
<li class="chapter" data-level="5.2.12" data-path="modelos-estacionarios.html"><a href="modelos-estacionarios.html#pronóstico-con-regresores-adicionales."><i class="fa fa-check"></i><b>5.2.12</b> Pronóstico con regresores adicionales.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="modelo-prophet.html"><a href="modelo-prophet.html"><i class="fa fa-check"></i><b>6</b> MODELO PROPHET</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de tiempo - Remesas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-estacionarios" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> MODELOS ESTACIONARIOS<a href="modelos-estacionarios.html#modelos-estacionarios" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<pre><code>##   Fecha_Pago Monto_USD Dia_semana
## 1 2023-01-01  314473.1     dom\\.
## 2 2023-01-02 4700346.1     lun\\.
## 3 2023-01-03 6069974.1     mar\\.
## 4 2023-01-04 6164948.9     mié\\.
## 5 2023-01-05 6986643.0     jue\\.
## 6 2023-01-06 6616416.0     vie\\.</code></pre>
<div id="metodología-box-jenkins" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> METODOLOGÍA BOX-JENKINS<a href="modelos-estacionarios.html#metodología-box-jenkins" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="visualizacion-de-la-serie" class="section level3 hasAnchor" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Visualizacion de la serie<a href="modelos-estacionarios.html#visualizacion-de-la-serie" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
</div>
<div id="verificación-de-estacionariedad" class="section level3 hasAnchor" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Verificación de estacionariedad<a href="modelos-estacionarios.html#verificación-de-estacionariedad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  Datos_FP_ts
## Dickey-Fuller = -7.4089, Lag order = 8, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
</div>
<div id="análisis-acf-y-pacf" class="section level3 hasAnchor" number="5.1.3">
<h3><span class="header-section-number">5.1.3</span> Análisis ACF y PACF<a href="modelos-estacionarios.html#análisis-acf-y-pacf" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-52-1.png" width="672" /><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-52-2.png" width="672" /></p>
</div>
<div id="ajuste-del-modelo" class="section level3 hasAnchor" number="5.1.4">
<h3><span class="header-section-number">5.1.4</span> Ajuste del modelo<a href="modelos-estacionarios.html#ajuste-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## Series: serie_xtsp 
## ARIMA(1,0,0)(2,1,0)[7] with drift 
## 
## Coefficients:
##          ar1     sar1     sar2     drift
##       0.2856  -0.6158  -0.3103  5325.258
## s.e.  0.0381   0.0377   0.0377  6663.866
## 
## sigma^2 = 2.627e+12:  log likelihood = -10090.17
## AIC=20190.34   AICc=20190.44   BIC=20212.67
## 
## Training set error measures:
##                     ME    RMSE     MAE       MPE     MAPE      MASE        ACF1
## Training set -1831.682 1607013 1084512 -8.691848 21.92267 0.7719142 -0.03913131</code></pre>
</div>
<div id="pronóstico" class="section level3 hasAnchor" number="5.1.5">
<h3><span class="header-section-number">5.1.5</span> Pronóstico<a href="modelos-estacionarios.html#pronóstico" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>##          Point Forecast     Lo 80    Hi 80     Lo 95    Hi 95
## 93.71429        9184204 7107055.4 11261352 6007479.4 12360929
## 93.85714        7598607 5438378.7  9758835 4294822.9 10902391
## 94.00000        2700759  533892.4  4867626 -613177.5  6014695
## 94.14286        9661864 7494456.3 11829271 6347100.2 12976627
## 94.28571        9861905 7694453.4 12029356 6547073.9 13176736
## 94.42857        9321229 7153773.9 11488684 6006392.5 12636065
## 94.57143        9239938 7072483.0 11407394 5925101.4 12554775
## 94.71429        9554357 7244521.0 11864193 6021767.8 13086946
## 94.85714        7793031 5471963.3 10114099 4243264.2 11342798
## 95.00000        2816478  494495.9  5138460 -734687.1  6367643
## 95.14286        9979647 7657590.8 12301704 6428368.4 13530926
## 95.28571       10443129 8121066.3 12765191 6891840.6 13994417</code></pre>
</div>
</div>
<div id="inclución-de-variables-en-el-tiempo-y-ajustes-a-un-modelo-lineal-y-estacionario" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> INCLUCIÓN DE VARIABLES EN EL TIEMPO Y AJUSTES A UN MODELO LINEAL Y ESTACIONARIO<a href="modelos-estacionarios.html#inclución-de-variables-en-el-tiempo-y-ajustes-a-un-modelo-lineal-y-estacionario" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="creación-de-variables-temporales-a-partir-de-la-fecha-de-pago" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Creación de variables temporales a partir de la fecha de pago<a href="modelos-estacionarios.html#creación-de-variables-temporales-a-partir-de-la-fecha-de-pago" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se crean las variables Dia_Anio, Mes, Semana y Es_Fin_de_Semana</p>
</div>
<div id="verificacion-de-la-misma-cobertura-de-fechas-de-las-dos-fuentes." class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Verificacion de la misma cobertura de fechas de las dos fuentes.<a href="modelos-estacionarios.html#verificacion-de-la-misma-cobertura-de-fechas-de-las-dos-fuentes." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para combinar datos adicionales con la serie de tiempo y usarlos como regresores en un modelo, es fundamental asegurarque los datos Datos_FP están correctamente alineados con el índice temporal de la serie Datos_FP_ts</p>
<pre><code>## [1] &quot;2023-01-01&quot; &quot;2023-01-02&quot; &quot;2023-01-03&quot; &quot;2023-01-04&quot; &quot;2023-01-05&quot; &quot;2023-01-06&quot;</code></pre>
<pre><code>## [1] 2023    1</code></pre>
</div>
<div id="agregar-las-variables-al-índice-de-la-serie" class="section level3 hasAnchor" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Agregar las variables al índice de la serie<a href="modelos-estacionarios.html#agregar-las-variables-al-índice-de-la-serie" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="modelos-estacionarios.html#cb31-1" tabindex="-1"></a><span class="co"># Crear un índice de fechas para la serie</span></span>
<span id="cb31-2"><a href="modelos-estacionarios.html#cb31-2" tabindex="-1"></a>Datos_FP<span class="sc">$</span>Fecha_Pago <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(Datos_FP<span class="sc">$</span>Fecha_Pago)</span>
<span id="cb31-3"><a href="modelos-estacionarios.html#cb31-3" tabindex="-1"></a></span>
<span id="cb31-4"><a href="modelos-estacionarios.html#cb31-4" tabindex="-1"></a><span class="co"># Alinear la serie con las fechas de Datos_FP</span></span>
<span id="cb31-5"><a href="modelos-estacionarios.html#cb31-5" tabindex="-1"></a>serie_alineada <span class="ot">&lt;-</span> <span class="fu">ts</span>(Datos_FP<span class="sc">$</span>Monto_USD, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2023</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">365</span>)</span></code></pre></div>
</div>
<div id="unión-de-las-variables-adicionales" class="section level3 hasAnchor" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Unión de las variables adicionales<a href="modelos-estacionarios.html#unión-de-las-variables-adicionales" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="modelos-estacionarios.html#cb32-1" tabindex="-1"></a><span class="co"># Fusionar la serie de tiempo con las variables adicionales</span></span>
<span id="cb32-2"><a href="modelos-estacionarios.html#cb32-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb32-3"><a href="modelos-estacionarios.html#cb32-3" tabindex="-1"></a></span>
<span id="cb32-4"><a href="modelos-estacionarios.html#cb32-4" tabindex="-1"></a><span class="co"># Asegúrate de que las fechas de la serie correspondan a las de Datos_FP</span></span>
<span id="cb32-5"><a href="modelos-estacionarios.html#cb32-5" tabindex="-1"></a>datos_combinados <span class="ot">&lt;-</span> Datos_FP <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="modelos-estacionarios.html#cb32-6" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Datos_FP_ts =</span> serie_alineada) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="modelos-estacionarios.html#cb32-7" tabindex="-1"></a>  <span class="fu">select</span>(Fecha_Pago, Datos_FP_ts, Dia_Anio, Mes, Semana, Es_Fin_de_Semana)</span></code></pre></div>
</div>
<div id="preparar" class="section level3 hasAnchor" number="5.2.5">
<h3><span class="header-section-number">5.2.5</span> Preparar<a href="modelos-estacionarios.html#preparar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se extraen las columnas de las variables adicionales que se usaran como regresores usando xreg.</p>
</div>
<div id="ajuste-del-modelo-arimax-con-los-datos-combinados-y-xreg." class="section level3 hasAnchor" number="5.2.6">
<h3><span class="header-section-number">5.2.6</span> Ajuste del modelo ARIMAX Con los datos combinados y xreg.<a href="modelos-estacionarios.html#ajuste-del-modelo-arimax-con-los-datos-combinados-y-xreg." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>## Series: serie_alineada 
## Regression with ARIMA(2,1,1) errors 
## 
## Coefficients:
##          ar1      ar2      ma1      drift   Dia_Anio        Mes      Semana  Es_Fin_de_Semana
##       0.1203  -0.0724  -0.9823  -5053.713  506543.96  1409040.8  -3792392.0        -3260731.8
## s.e.  0.0503   0.0402   0.0092   1450.510   41727.56   228661.6    276789.9          143782.4
## 
## sigma^2 = 2.477e+12:  log likelihood = -10163.4
## AIC=20344.79   AICc=20345.07   BIC=20385.06
## 
## Training set error measures:
##                    ME    RMSE     MAE       MPE     MAPE      MASE          ACF1
## Training set 22500.38 1562845 1154910 -11.31773 25.60318 0.4386007 -0.0004064767</code></pre>
<p>El resultado obtenido del ajuste del modelo ARIMA con variables exógenas (<code>SARIMAX</code>) proporciona varios indicadores y coeficientes:</p>
</div>
<div id="resumen-de-los-coeficientes" class="section level3 hasAnchor" number="5.2.7">
<h3><span class="header-section-number">5.2.7</span> <strong>Resumen de los Coeficientes:</strong><a href="modelos-estacionarios.html#resumen-de-los-coeficientes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>AR(1) y AR(2)</strong>: Estos son los coeficientes del modelo autorregresivo (AR), que indican cómo los valores pasados de la serie temporal (el valor en el tiempo <span class="math inline">\(t-1\)</span> y <span class="math inline">\(t-2\)</span>) influyen en el valor actual.
Los coeficientes son:</p>
<ul>
<li><span class="math inline">\(\text{AR(1)} = 0.1203\)</span></li>
<li><span class="math inline">\(\text{AR(2)} = -0.0724\)</span> Estos valores sugieren una relación débil entre los valores pasados de la serie temporal y el valor actual (dado que ambos coeficientes son relativamente pequeños).</li>
</ul></li>
<li><p><strong>MA(1)</strong>: Coeficiente del modelo de medias móviles; refleja cómo los errores pasados (residuos) afectan los valores actuales.
El coeficiente es:</p>
<ul>
<li><span class="math inline">\(\text{MA(1)} = -0.9823\)</span> Esto indica que los errores pasados tienen una fuerte influencia sobre la predicción actual.</li>
</ul></li>
<li><p><strong>Drift</strong>: Este término representa una tendencia en los datos.
Un valor negativo -5053.713 puede indicar que hay una tendencia decreciente a lo largo del tiempo.</p></li>
<li><p><strong>Variables exógenas</strong>:</p>
<ul>
<li><strong>Dia_Anio</strong>: El coeficiente <span class="math inline">\(506543.96\)</span> sugiere que el día del año tiene una relación positiva con la variable dependiente, aunque el valor es extremadamente grande, lo que podría indicar una escala incorrecta o un outlier en esos datos.</li>
<li><strong>Mes</strong>: El coeficiente <span class="math inline">\(1409040.8\)</span> también es grande, lo que sugiere una fuerte influencia de la variable mes en la serie temporal.</li>
<li><strong>Semana</strong>: El coeficiente <span class="math inline">\(-3792392.0\)</span> es negativo y bastante grande en valor absoluto, lo que implica que las semanas tienen un impacto considerable pero contrario al comportamiento de la variable dependiente.</li>
<li><strong>Es_Fin_de_Semana</strong>: El coeficiente <span class="math inline">\(-3260731.8\)</span> indica que, si es fin de semana, la variable dependiente tiende a ser más baja (dado que es negativo).</li>
</ul></li>
<li><p><strong>Errores estándar (s.e.)</strong>: Los errores estándar asociados a cada coeficiente indican la variabilidad de las estimaciones.
Si el coeficiente es mucho mayor que el error estándar, el coeficiente es más significativo.</p></li>
</ul>
<hr />
</div>
<div id="métricas-del-modelo" class="section level3 hasAnchor" number="5.2.8">
<h3><span class="header-section-number">5.2.8</span> <strong>Métricas del Modelo:</strong><a href="modelos-estacionarios.html#métricas-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><span class="math inline">\(\sigma^2 = 2.477e+12\)</span>: Este es el estimado de la varianza del error (residual).
Un valor muy grande podría sugerir que hay alta variabilidad en los residuos y que el modelo no captura toda la variabilidad en los datos.</p></li>
<li><p><strong>Log-likelihood = -10163.4</strong>: El logaritmo de la verosimilitud se utiliza para evaluar el ajuste del modelo.
Un valor más alto (menos negativo) indica un mejor ajuste.</p></li>
<li><p><strong>AIC = 20344.79</strong>: El <strong>Akaike Information Criterion</strong> (AIC) penaliza la complejidad del modelo (número de parámetros) y ayuda a elegir el modelo más parsimonioso (el que ajusta bien pero con menos parámetros).
En general, cuanto menor es el AIC, mejor es el modelo.</p></li>
<li><p><strong>AICc = 20345.07</strong>: Este es el AIC corregido para el tamaño de la muestra, lo cual es útil cuando el número de observaciones es pequeño en relación con el número de parámetros del modelo.</p></li>
<li><p><strong>BIC = 20385.06</strong>: El <strong>Bayesian Information Criterion</strong> (BIC) es similar al AIC, pero penaliza aún más la complejidad del modelo.
Un valor más bajo es preferible.</p></li>
</ul>
<hr />
</div>
<div id="errores-en-el-conjunto-de-entrenamiento" class="section level3 hasAnchor" number="5.2.9">
<h3><span class="header-section-number">5.2.9</span> <strong>Errores en el conjunto de entrenamiento:</strong><a href="modelos-estacionarios.html#errores-en-el-conjunto-de-entrenamiento" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Las métricas del modelo sobre el conjunto de entrenamiento son importantes para evaluar el desempeño: - <strong>ME (Mean Error)</strong> = 22500.38: Es el error promedio, que muestra si el modelo tiene un sesgo sistemático.
En este caso, un valor relativamente alto sugiere que el modelo puede tener un sesgo (tal vez está sobreestimando los valores).
- <strong>RMSE (Root Mean Squared Error)</strong> = 1,562,845: Mide el error promedio entre los valores observados y los predichos.
Es bastante alto, lo que sugiere que el modelo no está prediciendo con gran precisión.
- <strong>MAE (Mean Absolute Error)</strong> = 1,154,910: Similar al RMSE, pero no toma en cuenta la dirección del error.
También es bastante alto, lo que indica un ajuste no óptimo.
- <strong>MPE (Mean Percentage Error)</strong> = -11.32: Este valor negativo sugiere que el modelo tiende a subestimar las predicciones en promedio.
- <strong>MAPE (Mean Absolute Percentage Error)</strong> = 25.60: Es el error absoluto en términos porcentuales.
En este caso, el modelo tiene un error del 25.6% en promedio, lo cual no es ideal, especialmente si el modelo se aplica en situaciones donde la precisión es crucial.
- <strong>MASE (Mean Absolute Scaled Error)</strong> = 0.4386: Es una métrica que compara el desempeño del modelo con un modelo simple de referencia (como un modelo que siempre predice la media).
Un valor menor a 1 indica que el modelo es mejor que el modelo de referencia.
- <strong>ACF1 (Autocorrelation Function lag 1)</strong> = -0.0004: Indica la correlación entre los residuos en el primer retardo.
Un valor cercano a cero sugiere que los residuos no están autocorrelacionados, lo cual es una buena señal.</p>
<hr />
</div>
<div id="validación" class="section level3 hasAnchor" number="5.2.10">
<h3><span class="header-section-number">5.2.10</span> Validación<a href="modelos-estacionarios.html#validación" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from Regression with ARIMA(2,1,1) errors
## Q* = 917.06, df = 127, p-value &lt; 2.2e-16
## 
## Model df: 3.   Total lags used: 130</code></pre>
<pre><code>##              ar1              ar2              ma1            drift         Dia_Anio              Mes 
##     1.203421e-01    -7.239999e-02    -9.822696e-01    -5.053713e+03     5.065440e+05     1.409041e+06 
##           Semana Es_Fin_de_Semana 
##    -3.792392e+06    -3.260732e+06</code></pre>
</div>
<div id="ljung-box-test" class="section level3 hasAnchor" number="5.2.11">
<h3><span class="header-section-number">5.2.11</span> <strong>Ljung-Box test:</strong><a href="modelos-estacionarios.html#ljung-box-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p><strong>Q* = 917.06, df = 127, p-value &lt; 2.2e-16</strong>: El <strong>Ljung-Box test</strong> se utiliza para verificar si hay autocorrelación en los residuos del modelo. Específicamente, prueba si los residuos están correlacionados en un conjunto de retardos (lags).</p>
<ul>
<li><strong>Q* = 917.06</strong>: Este es el estadístico de prueba, que mide la cantidad de autocorrelación en los residuos.</li>
<li><strong>df = 127</strong>: Los grados de libertad del test, que se corresponden con los retardos que se han usado en la prueba. En este caso, se han utilizado 130 retardos para evaluar la autocorrelación.</li>
<li><strong>p-value &lt; 2.2e-16</strong>: El valor p es extremadamente pequeño, lo que indica que <strong>hay evidencia significativa de autocorrelación</strong> en los residuos. En otras palabras, el modelo no está capturando toda la estructura temporal de los datos.</li>
</ul></li>
</ul>
<p>El <strong>Ljung-Box test</strong> con un valor p tan bajo (casi igual a cero) indica que los residuos del modelo no son completamente aleatorios y contienen patrones de autocorrelación no capturados por el modelo. Esto sugiere que el modelo <code>ARIMAX(2,1,1)</code> no es totalmente adecuado para los datos, y probablemente hay alguna estructura temporal en los residuos que el modelo no ha logrado ajustar.</p>
</div>
<div id="pronóstico-con-regresores-adicionales." class="section level3 hasAnchor" number="5.2.12">
<h3><span class="header-section-number">5.2.12</span> Pronóstico con regresores adicionales.<a href="modelos-estacionarios.html#pronóstico-con-regresores-adicionales." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Al realizar pronósticos, es necesario generar valores futuros para los regresores:</p>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="holt---winters.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-prophet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/5_Modelos_estacionarios.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Remesas en dolares.pdf", "Remesas en dolares.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
