<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 PREPROCESAMIENTO Y VISUALIZACION | Series de tiempo - Remesas</title>
  <meta name="description" content="3 PREPROCESAMIENTO Y VISUALIZACION | Series de tiempo - Remesas" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="3 PREPROCESAMIENTO Y VISUALIZACION | Series de tiempo - Remesas" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 PREPROCESAMIENTO Y VISUALIZACION | Series de tiempo - Remesas" />
  
  
  

<meta name="author" content="Analisis de Series de Tiempo Grupo 5 - William Contreras, Camilo Espinoza, Jorge Agredo" />


<meta name="date" content="2024-11-04" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="descripción-de-las-series-de-tiempo.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="remesas.html"><a href="remesas.html"><i class="fa fa-check"></i><b>1</b> REMESAS</a>
<ul>
<li class="chapter" data-level="1.1" data-path="remesas.html"><a href="remesas.html#introducción"><i class="fa fa-check"></i><b>1.1</b> INTRODUCCIÓN</a></li>
<li class="chapter" data-level="1.2" data-path="remesas.html"><a href="remesas.html#base-de-datos"><i class="fa fa-check"></i><b>1.2</b> BASE DE DATOS</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html"><i class="fa fa-check"></i><b>2</b> DESCRIPCIÓN DE LAS SERIES DE TIEMPO</a>
<ul>
<li class="chapter" data-level="2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>2.1</b> Serie de tiempo por Fecha de Pago</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts"><i class="fa fa-check"></i><b>2.1.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.1.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo"><i class="fa fa-check"></i><b>2.1.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.1.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles"><i class="fa fa-check"></i><b>2.1.3</b> Promedios móviles</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#serie-de-tiempo-por-fecha-de-origen"><i class="fa fa-check"></i><b>2.2</b> Serie de tiempo por Fecha de Origen</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#uso-de-la-librería-xts-1"><i class="fa fa-check"></i><b>2.2.1</b> Uso de la librería “XTS”</a></li>
<li class="chapter" data-level="2.2.2" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#gráfico-de-rezago-para-la-serie-de-tiempo-1"><i class="fa fa-check"></i><b>2.2.2</b> Gráfico de rezago para la serie de tiempo</a></li>
<li class="chapter" data-level="2.2.3" data-path="descripción-de-las-series-de-tiempo.html"><a href="descripción-de-las-series-de-tiempo.html#promedios-móviles-1"><i class="fa fa-check"></i><b>2.2.3</b> Promedios móviles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html"><i class="fa fa-check"></i><b>3</b> PREPROCESAMIENTO Y VISUALIZACION</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#descomposición-estacionariedad-y-diferenciación---serie-de-tiempo-por-fecha-de-pago"><i class="fa fa-check"></i><b>3.1</b> Descomposición, estacionariedad y diferenciación - Serie de tiempo por Fecha de Pago</a></li>
<li class="chapter" data-level="3.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#verificar-si-la-serie-es-esacionaria"><i class="fa fa-check"></i><b>3.2</b> Verificar si la serie es esacionaria</a></li>
<li class="chapter" data-level="3.3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#funciones-acf-y-pacf"><i class="fa fa-check"></i><b>3.3</b> Funciones acf y pacf</a></li>
<li class="chapter" data-level="3.4" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#modelo-arima"><i class="fa fa-check"></i><b>3.4</b> Modelo ARIMA</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#modelo-arima-1"><i class="fa fa-check"></i><b>3.4.1</b> <strong>Modelo ARIMA</strong></a></li>
<li class="chapter" data-level="3.4.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#coeficientes-del-modelo"><i class="fa fa-check"></i><b>3.4.2</b> <strong>Coeficientes del Modelo</strong></a></li>
<li class="chapter" data-level="3.4.3" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#errores-estándar-s.e."><i class="fa fa-check"></i><b>3.4.3</b> <strong>Errores Estándar (s.e.)</strong></a></li>
<li class="chapter" data-level="3.4.4" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#sigma2"><i class="fa fa-check"></i><b>3.4.4</b> <strong>Sigma^2</strong></a></li>
<li class="chapter" data-level="3.4.5" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#log-likelihood-aic-aicc-bic"><i class="fa fa-check"></i><b>3.4.5</b> <strong>Log Likelihood, AIC, AICc, BIC</strong></a></li>
<li class="chapter" data-level="3.4.6" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#resumen"><i class="fa fa-check"></i><b>3.4.6</b> Resumen</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#diagnóstico-del-modelo."><i class="fa fa-check"></i><b>3.5</b> Diagnóstico del modelo.</a></li>
<li class="chapter" data-level="3.6" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#prediccones-del-modelo-arima"><i class="fa fa-check"></i><b>3.6</b> Prediccones del Modelo ARIMA</a></li>
<li class="chapter" data-level="3.7" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#punto-de-cambio-de-la-serie-de-tiempo"><i class="fa fa-check"></i><b>3.7</b> Punto de cambio de la serie de tiempo</a></li>
<li class="chapter" data-level="3.8" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#gráfica-acf-y-pacf-de-los-residuos"><i class="fa fa-check"></i><b>3.8</b> Gráfica ACF y PACF de los residuos</a></li>
<li class="chapter" data-level="3.9" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#prueba-de-ljung-box"><i class="fa fa-check"></i><b>3.9</b> Prueba de Ljung-Box</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#interpretación-de-los-resultados"><i class="fa fa-check"></i><b>3.9.1</b> Interpretación de los Resultados</a></li>
<li class="chapter" data-level="3.9.2" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#conclusión"><i class="fa fa-check"></i><b>3.9.2</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#normalidad-de-los-residuos"><i class="fa fa-check"></i><b>3.10</b> Normalidad de los residuos</a></li>
<li class="chapter" data-level="3.11" data-path="preprocesamiento-y-visualizacion.html"><a href="preprocesamiento-y-visualizacion.html#gráfico-q-q-quantile-quantile"><i class="fa fa-check"></i><b>3.11</b> Gráfico Q-Q (Quantile-Quantile)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de tiempo - Remesas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="preprocesamiento-y-visualizacion" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> PREPROCESAMIENTO Y VISUALIZACION<a href="preprocesamiento-y-visualizacion.html#preprocesamiento-y-visualizacion" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="descomposición-estacionariedad-y-diferenciación---serie-de-tiempo-por-fecha-de-pago" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Descomposición, estacionariedad y diferenciación - Serie de tiempo por Fecha de Pago<a href="preprocesamiento-y-visualizacion.html#descomposición-estacionariedad-y-diferenciación---serie-de-tiempo-por-fecha-de-pago" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="preprocesamiento-y-visualizacion.html#cb13-1" tabindex="-1"></a><span class="co">#install.packages(&quot;zoo&quot;)</span></span>
<span id="cb13-2"><a href="preprocesamiento-y-visualizacion.html#cb13-2" tabindex="-1"></a><span class="fu">library</span>(TTR)</span>
<span id="cb13-3"><a href="preprocesamiento-y-visualizacion.html#cb13-3" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb13-4"><a href="preprocesamiento-y-visualizacion.html#cb13-4" tabindex="-1"></a></span>
<span id="cb13-5"><a href="preprocesamiento-y-visualizacion.html#cb13-5" tabindex="-1"></a><span class="co"># Convertir el objeto &#39;Datos_FP&#39; en un ts con frecuencia semanal (si aplica)</span></span>
<span id="cb13-6"><a href="preprocesamiento-y-visualizacion.html#cb13-6" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2023-01-01&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2024-10-10&quot;</span>), <span class="at">by =</span> <span class="st">&quot;day&quot;</span>)</span>
<span id="cb13-7"><a href="preprocesamiento-y-visualizacion.html#cb13-7" tabindex="-1"></a>serie_ts <span class="ot">&lt;-</span> <span class="fu">zoo</span>(Datos_FP<span class="sc">$</span>Monto_USD, <span class="at">order.by =</span> fechas)</span>
<span id="cb13-8"><a href="preprocesamiento-y-visualizacion.html#cb13-8" tabindex="-1"></a><span class="co">#serie_ts_fo &lt;- zoo(Datos_FO$Monto_USD, order.by = fechas)</span></span></code></pre></div>
</div>
<div id="verificar-si-la-serie-es-esacionaria" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Verificar si la serie es esacionaria<a href="preprocesamiento-y-visualizacion.html#verificar-si-la-serie-es-esacionaria" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="preprocesamiento-y-visualizacion.html#cb14-1" tabindex="-1"></a><span class="co"># Verificar si la serie es estacionaria</span></span>
<span id="cb14-2"><a href="preprocesamiento-y-visualizacion.html#cb14-2" tabindex="-1"></a><span class="co"># Instala y carga la librería si aún no la tienes</span></span>
<span id="cb14-3"><a href="preprocesamiento-y-visualizacion.html#cb14-3" tabindex="-1"></a><span class="co">#install.packages(&quot;tseries&quot;)</span></span>
<span id="cb14-4"><a href="preprocesamiento-y-visualizacion.html#cb14-4" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb14-5"><a href="preprocesamiento-y-visualizacion.html#cb14-5" tabindex="-1"></a></span>
<span id="cb14-6"><a href="preprocesamiento-y-visualizacion.html#cb14-6" tabindex="-1"></a><span class="co"># Aplica la prueba ADF a tu serie de tiempo</span></span>
<span id="cb14-7"><a href="preprocesamiento-y-visualizacion.html#cb14-7" tabindex="-1"></a>adf_test <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(serie_ts)</span>
<span id="cb14-8"><a href="preprocesamiento-y-visualizacion.html#cb14-8" tabindex="-1"></a><span class="fu">print</span>(adf_test)</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  serie_ts
## Dickey-Fuller = -7.4089, Lag order = 8, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<p>El resultado de la prueba Dickey-Fuller Aumentada (ADF) indica que la serie es <strong>estacionaria</strong> por lo cual no requiere de ninguna transformacion.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Estadístico de Dickey-Fuller = -7.4089</strong>: Este es el valor calculado para el estadístico de prueba. Un valor más negativo tiende a indicar estacionariedad, ya que refuerza el rechazo de la hipótesis nula de no estacionariedad.</p></li>
<li><p><strong>p-value = 0.01</strong>: Este p-valor es bajo (generalmente menor a 0.05 es un umbral común para significancia). Dado que el p-valor es 0.01, puedes rechazar la hipótesis nula de no estacionariedad con un 99% de confianza. Esto significa que hay una fuerte evidencia de que tu serie es estacionaria.</p></li>
<li><p><strong>alternative hypothesis: stationary</strong>: La hipótesis alternativa de la prueba es que la serie es estacionaria. Dado que el p-valor es bajo, este resultado respalda la hipótesis alternativa, indicando estacionariedad.</p></li>
</ol>
<p>En resumen, se puede concluir concluir que la serie es estacionaria con un nivel de confianza alto. Esto significa que sus propiedades estadísticas, como la media y la varianza, se mantienen constantes a lo largo del tiempo, lo cual es un buen punto de partida para aplicar modelos de series de tiempo como ARIMA, que asumen estacionariedad.</p>
</div>
<div id="funciones-acf-y-pacf" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Funciones acf y pacf<a href="preprocesamiento-y-visualizacion.html#funciones-acf-y-pacf" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="preprocesamiento-y-visualizacion.html#cb16-1" tabindex="-1"></a><span class="co"># Cargar librerías necesarias</span></span>
<span id="cb16-2"><a href="preprocesamiento-y-visualizacion.html#cb16-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb16-3"><a href="preprocesamiento-y-visualizacion.html#cb16-3" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb16-4"><a href="preprocesamiento-y-visualizacion.html#cb16-4" tabindex="-1"></a></span>
<span id="cb16-5"><a href="preprocesamiento-y-visualizacion.html#cb16-5" tabindex="-1"></a><span class="co"># Crear gráficos ACF y PACF</span></span>
<span id="cb16-6"><a href="preprocesamiento-y-visualizacion.html#cb16-6" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>)) <span class="co"># Configura el área de gráficos</span></span>
<span id="cb16-7"><a href="preprocesamiento-y-visualizacion.html#cb16-7" tabindex="-1"></a></span>
<span id="cb16-8"><a href="preprocesamiento-y-visualizacion.html#cb16-8" tabindex="-1"></a><span class="co"># Gráfico ACF</span></span>
<span id="cb16-9"><a href="preprocesamiento-y-visualizacion.html#cb16-9" tabindex="-1"></a><span class="fu">acf</span>(serie_ts, <span class="at">main =</span> <span class="st">&quot;Función de Autocorrelacion (ACF)&quot;</span>, <span class="at">lag.max =</span> <span class="dv">7</span>)</span>
<span id="cb16-10"><a href="preprocesamiento-y-visualizacion.html#cb16-10" tabindex="-1"></a></span>
<span id="cb16-11"><a href="preprocesamiento-y-visualizacion.html#cb16-11" tabindex="-1"></a><span class="co"># Gráfico PACF</span></span>
<span id="cb16-12"><a href="preprocesamiento-y-visualizacion.html#cb16-12" tabindex="-1"></a><span class="fu">pacf</span>(serie_ts, <span class="at">main =</span> <span class="st">&quot;Función de Autocorrelacion Parcial (PACF)&quot;</span>, <span class="at">lag.max =</span> <span class="dv">7</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="preprocesamiento-y-visualizacion.html#cb17-1" tabindex="-1"></a><span class="co"># Restaurar configuración de gráficos</span></span>
<span id="cb17-2"><a href="preprocesamiento-y-visualizacion.html#cb17-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="preprocesamiento-y-visualizacion.html#cb18-1" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb18-2"><a href="preprocesamiento-y-visualizacion.html#cb18-2" tabindex="-1"></a></span>
<span id="cb18-3"><a href="preprocesamiento-y-visualizacion.html#cb18-3" tabindex="-1"></a><span class="co">#install.packages(&quot;TTR&quot;)</span></span>
<span id="cb18-4"><a href="preprocesamiento-y-visualizacion.html#cb18-4" tabindex="-1"></a></span>
<span id="cb18-5"><a href="preprocesamiento-y-visualizacion.html#cb18-5" tabindex="-1"></a><span class="co"># Asegurarnos de que la frecuencia corresponde al periodo deseado</span></span>
<span id="cb18-6"><a href="preprocesamiento-y-visualizacion.html#cb18-6" tabindex="-1"></a><span class="co">#serie_ts &lt;- ts(Datos_FP$Monto_USD, frequency = 365, start = c(2023, 1))</span></span>
<span id="cb18-7"><a href="preprocesamiento-y-visualizacion.html#cb18-7" tabindex="-1"></a> </span>
<span id="cb18-8"><a href="preprocesamiento-y-visualizacion.html#cb18-8" tabindex="-1"></a><span class="co"># Calcula la tendencia usando una media móvil, ajusta el número de periodos según sea necesario</span></span>
<span id="cb18-9"><a href="preprocesamiento-y-visualizacion.html#cb18-9" tabindex="-1"></a>tendencia <span class="ot">&lt;-</span> <span class="fu">SMA</span>(Datos_FP<span class="sc">$</span>Monto_USD, <span class="at">n =</span> <span class="dv">30</span>) <span class="co"># Media móvil de 30 días</span></span>
<span id="cb18-10"><a href="preprocesamiento-y-visualizacion.html#cb18-10" tabindex="-1"></a> </span>
<span id="cb18-11"><a href="preprocesamiento-y-visualizacion.html#cb18-11" tabindex="-1"></a><span class="co"># Calcula la estacionalidad (residuo de los datos menos la tendencia)</span></span>
<span id="cb18-12"><a href="preprocesamiento-y-visualizacion.html#cb18-12" tabindex="-1"></a>estacionalidad <span class="ot">&lt;-</span> Datos_FP<span class="sc">$</span>Monto_USD <span class="sc">-</span> tendencia</span>
<span id="cb18-13"><a href="preprocesamiento-y-visualizacion.html#cb18-13" tabindex="-1"></a> </span>
<span id="cb18-14"><a href="preprocesamiento-y-visualizacion.html#cb18-14" tabindex="-1"></a><span class="co"># Promedia por semana para capturar un patrón estacional semanal</span></span>
<span id="cb18-15"><a href="preprocesamiento-y-visualizacion.html#cb18-15" tabindex="-1"></a>estacionalidad_media <span class="ot">&lt;-</span> <span class="fu">tapply</span>(estacionalidad, <span class="fu">as.POSIXlt</span>(fechas)<span class="sc">$</span>yday <span class="sc">%%</span> <span class="dv">7</span>, mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-16"><a href="preprocesamiento-y-visualizacion.html#cb18-16" tabindex="-1"></a>estacionalidad <span class="ot">&lt;-</span> <span class="fu">rep</span>(estacionalidad_media, <span class="at">length.out =</span> <span class="fu">length</span>(Datos_FP<span class="sc">$</span>Monto_USD))</span>
<span id="cb18-17"><a href="preprocesamiento-y-visualizacion.html#cb18-17" tabindex="-1"></a> </span>
<span id="cb18-18"><a href="preprocesamiento-y-visualizacion.html#cb18-18" tabindex="-1"></a><span class="co"># Calcula el residuo (parte aleatoria)</span></span>
<span id="cb18-19"><a href="preprocesamiento-y-visualizacion.html#cb18-19" tabindex="-1"></a>residuo <span class="ot">&lt;-</span> Datos_FP<span class="sc">$</span>Monto_USD <span class="sc">-</span> tendencia <span class="sc">-</span> estacionalidad</span>
<span id="cb18-20"><a href="preprocesamiento-y-visualizacion.html#cb18-20" tabindex="-1"></a> </span>
<span id="cb18-21"><a href="preprocesamiento-y-visualizacion.html#cb18-21" tabindex="-1"></a><span class="co">#library(ggplot2)</span></span>
<span id="cb18-22"><a href="preprocesamiento-y-visualizacion.html#cb18-22" tabindex="-1"></a></span>
<span id="cb18-23"><a href="preprocesamiento-y-visualizacion.html#cb18-23" tabindex="-1"></a></span>
<span id="cb18-24"><a href="preprocesamiento-y-visualizacion.html#cb18-24" tabindex="-1"></a>df_componentes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-25"><a href="preprocesamiento-y-visualizacion.html#cb18-25" tabindex="-1"></a>  <span class="at">Fecha =</span> fechas,</span>
<span id="cb18-26"><a href="preprocesamiento-y-visualizacion.html#cb18-26" tabindex="-1"></a>  <span class="at">Datos =</span> Datos_FP<span class="sc">$</span>Monto_USD,</span>
<span id="cb18-27"><a href="preprocesamiento-y-visualizacion.html#cb18-27" tabindex="-1"></a>  <span class="at">Tendencia =</span> tendencia,</span>
<span id="cb18-28"><a href="preprocesamiento-y-visualizacion.html#cb18-28" tabindex="-1"></a>  <span class="at">Estacionalidad =</span> estacionalidad,</span>
<span id="cb18-29"><a href="preprocesamiento-y-visualizacion.html#cb18-29" tabindex="-1"></a>  <span class="at">Residuo =</span> residuo</span>
<span id="cb18-30"><a href="preprocesamiento-y-visualizacion.html#cb18-30" tabindex="-1"></a>)</span>
<span id="cb18-31"><a href="preprocesamiento-y-visualizacion.html#cb18-31" tabindex="-1"></a> </span>
<span id="cb18-32"><a href="preprocesamiento-y-visualizacion.html#cb18-32" tabindex="-1"></a><span class="co"># Graficar cada componente usando ggplot2</span></span>
<span id="cb18-33"><a href="preprocesamiento-y-visualizacion.html#cb18-33" tabindex="-1"></a><span class="fu">ggplot</span>(df_componentes, <span class="fu">aes</span>(<span class="at">x =</span> Fecha)) <span class="sc">+</span> </span>
<span id="cb18-34"><a href="preprocesamiento-y-visualizacion.html#cb18-34" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Datos)) <span class="sc">+</span> </span>
<span id="cb18-35"><a href="preprocesamiento-y-visualizacion.html#cb18-35" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Data&quot;</span>, <span class="at">y =</span> <span class="st">&quot;data&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="preprocesamiento-y-visualizacion.html#cb19-1" tabindex="-1"></a><span class="fu">ggplot</span>(df_componentes, <span class="fu">aes</span>(<span class="at">x =</span> Fecha)) <span class="sc">+</span> </span>
<span id="cb19-2"><a href="preprocesamiento-y-visualizacion.html#cb19-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Estacionalidad)) <span class="sc">+</span> </span>
<span id="cb19-3"><a href="preprocesamiento-y-visualizacion.html#cb19-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Estacionalidad&quot;</span>, <span class="at">y =</span> <span class="st">&quot;seasonal&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-25-2.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="preprocesamiento-y-visualizacion.html#cb20-1" tabindex="-1"></a><span class="fu">ggplot</span>(df_componentes, <span class="fu">aes</span>(<span class="at">x =</span> Fecha)) <span class="sc">+</span> </span>
<span id="cb20-2"><a href="preprocesamiento-y-visualizacion.html#cb20-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Tendencia)) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="preprocesamiento-y-visualizacion.html#cb20-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Tendencia&quot;</span>, <span class="at">y =</span> <span class="st">&quot;trend&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-25-3.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="preprocesamiento-y-visualizacion.html#cb21-1" tabindex="-1"></a><span class="fu">ggplot</span>(df_componentes, <span class="fu">aes</span>(<span class="at">x =</span> Fecha)) <span class="sc">+</span> </span>
<span id="cb21-2"><a href="preprocesamiento-y-visualizacion.html#cb21-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Residuo)) <span class="sc">+</span> </span>
<span id="cb21-3"><a href="preprocesamiento-y-visualizacion.html#cb21-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Residuo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;remainder&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-25-4.png" width="672" /></p>
</div>
<div id="modelo-arima" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Modelo ARIMA<a href="preprocesamiento-y-visualizacion.html#modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="preprocesamiento-y-visualizacion.html#cb22-1" tabindex="-1"></a>modelo_arima <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(serie_ts)</span>
<span id="cb22-2"><a href="preprocesamiento-y-visualizacion.html#cb22-2" tabindex="-1"></a><span class="fu">summary</span>(modelo_arima)</span></code></pre></div>
<pre><code>## Series: serie_ts 
## ARIMA(1,1,2) 
## 
## Coefficients:
##           ar1      ma1      ma2
##       -0.6595  -0.1343  -0.8306
## s.e.   0.0698   0.0500   0.0485
## 
## sigma^2 = 5.659e+12:  log likelihood = -10433.64
## AIC=20875.29   AICc=20875.35   BIC=20893.18
## 
## Training set error measures:
##                  ME    RMSE     MAE       MPE     MAPE      MASE       ACF1
## Training set 225291 2371592 1881706 -26.87723 51.80463 0.8184988 -0.0180491</code></pre>
<p>El resultado del <code>summary(modelo_arima)</code> obtenido brinda información detallada sobre el modelo ARIMA que se ha ajustado a la serie de tiempo.</p>
<div id="modelo-arima-1" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> <strong>Modelo ARIMA</strong><a href="preprocesamiento-y-visualizacion.html#modelo-arima-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>ARIMA(1,1,2)</strong>: Esto indica que el modelo es un ARIMA con los siguientes parámetros:
<ul>
<li><strong>1</strong>: Este número representa el orden autorregresivo <span class="math inline">\(p\)</span> (número de términos pasados de la serie que se incluyen).</li>
<li><strong>1</strong>: Este número representa el orden de diferenciación <span class="math inline">\(d\)</span> (número de veces que los datos se diferencian para lograr estacionariedad).</li>
<li><strong>2</strong>: Este número representa el orden de media móvil <span class="math inline">\(q\)</span> (número de términos pasados de los errores que se incluyen).</li>
</ul></li>
</ul>
</div>
<div id="coeficientes-del-modelo" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> <strong>Coeficientes del Modelo</strong><a href="preprocesamiento-y-visualizacion.html#coeficientes-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los coeficientes estimados del modelo son:</p>
<ul>
<li><p><strong>ar1</strong>: Este coeficiente está relacionado con el término autorregresivo del modelo. Un valor de <span class="math inline">\(-0.6595\)</span> sugiere que existe una relación negativa entre el valor actual y el valor pasado en la serie de tiempo. En otras palabras, si el valor en el período anterior es alto, el valor en el período actual tiende a ser bajo, y viceversa.</p></li>
<li><p><strong>ma1 y ma2</strong>: Estos coeficientes están relacionados con los términos de media móvil.</p>
<ul>
<li><strong>ma1 = -0.1343</strong>: Indica que el primer término de error tiene una relación negativa con el valor actual.</li>
<li><strong>ma2 = -0.8306</strong>: Este coeficiente tiene una relación negativa más fuerte, lo que sugiere que los errores de dos períodos atrás tienen un impacto considerable en el valor actual.</li>
</ul></li>
</ul>
</div>
<div id="errores-estándar-s.e." class="section level3 hasAnchor" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> <strong>Errores Estándar (s.e.)</strong><a href="preprocesamiento-y-visualizacion.html#errores-estándar-s.e." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los errores estándar asociados a cada coeficiente te dan una idea de la incertidumbre de estas estimaciones:
- <strong>s.e. ar1 = 0.0698</strong>
- <strong>s.e. ma1 = 0.0500</strong>
- <strong>s.e. ma2 = 0.0485</strong></p>
<p>Un error estándar pequeño en relación con el coeficiente indica que la estimación del coeficiente es relativamente precisa.</p>
</div>
<div id="sigma2" class="section level3 hasAnchor" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> <strong>Sigma^2</strong><a href="preprocesamiento-y-visualizacion.html#sigma2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>sigma^2 = 5.659e+12</strong>: Este valor representa la varianza de los residuos del modelo. Un valor más bajo indicaría un mejor ajuste del modelo, ya que implica que los errores (diferencias entre los valores reales y los valores ajustados) son pequeños.</li>
</ul>
</div>
<div id="log-likelihood-aic-aicc-bic" class="section level3 hasAnchor" number="3.4.5">
<h3><span class="header-section-number">3.4.5</span> <strong>Log Likelihood, AIC, AICc, BIC</strong><a href="preprocesamiento-y-visualizacion.html#log-likelihood-aic-aicc-bic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Log Likelihood = -10433.64</strong>: Este valor es utilizado para comparar modelos; más cerca de cero es mejor.</li>
<li><strong>AIC = 20875.29</strong>: El Criterio de Información de Akaike (AIC) se utiliza para comparar diferentes modelos. Un valor menor indica un mejor modelo, considerando la complejidad del modelo.</li>
<li><strong>AICc = 20875.35</strong>: Es una versión corregida del AIC que se aplica a muestras pequeñas. Se prefiere usarlo cuando la muestra es relativamente pequeña en comparación con la complejidad del modelo.</li>
<li><strong>BIC = 20893.18</strong>: El Criterio de Información de Bayesian (BIC) también se utiliza para la comparación de modelos, penalizando más fuertemente los modelos complejos que el AIC. Al igual que el AIC, un valor menor es mejor.</li>
</ul>
</div>
<div id="resumen" class="section level3 hasAnchor" number="3.4.6">
<h3><span class="header-section-number">3.4.6</span> Resumen<a href="preprocesamiento-y-visualizacion.html#resumen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El modelo ARIMA(1,1,2) sugiere que hay una relación significativa entre los valores pasados y los errores en la serie de tiempo. Además, los valores de AIC y BIC permitirán comparar este modelo con otros modelos que se podrían considerar para ver si hay mejores alternativas.</p>
</div>
</div>
<div id="diagnóstico-del-modelo." class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Diagnóstico del modelo.<a href="preprocesamiento-y-visualizacion.html#diagnóstico-del-modelo." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="preprocesamiento-y-visualizacion.html#cb24-1" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelo_arima)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,2)
## Q* = 329.69, df = 7, p-value &lt; 2.2e-16
## 
## Model df: 3.   Total lags used: 10</code></pre>
</div>
<div id="prediccones-del-modelo-arima" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Prediccones del Modelo ARIMA<a href="preprocesamiento-y-visualizacion.html#prediccones-del-modelo-arima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="preprocesamiento-y-visualizacion.html#cb26-1" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">forecast</span>(modelo_arima, <span class="at">h =</span> <span class="dv">12</span>)  <span class="co">#&#39;h&#39; indica cuántos períodos quieras predecir</span></span>
<span id="cb26-2"><a href="preprocesamiento-y-visualizacion.html#cb26-2" tabindex="-1"></a><span class="fu">plot</span>(predicciones)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
</div>
<div id="punto-de-cambio-de-la-serie-de-tiempo" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Punto de cambio de la serie de tiempo<a href="preprocesamiento-y-visualizacion.html#punto-de-cambio-de-la-serie-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="preprocesamiento-y-visualizacion.html#cb27-1" tabindex="-1"></a><span class="co"># Instalar el paquete changepoint si no lo tienes</span></span>
<span id="cb27-2"><a href="preprocesamiento-y-visualizacion.html#cb27-2" tabindex="-1"></a><span class="co">#install.packages(&quot;changepoint&quot;)</span></span>
<span id="cb27-3"><a href="preprocesamiento-y-visualizacion.html#cb27-3" tabindex="-1"></a></span>
<span id="cb27-4"><a href="preprocesamiento-y-visualizacion.html#cb27-4" tabindex="-1"></a><span class="co"># Cargar el paquete</span></span>
<span id="cb27-5"><a href="preprocesamiento-y-visualizacion.html#cb27-5" tabindex="-1"></a><span class="fu">library</span>(changepoint)</span>
<span id="cb27-6"><a href="preprocesamiento-y-visualizacion.html#cb27-6" tabindex="-1"></a></span>
<span id="cb27-7"><a href="preprocesamiento-y-visualizacion.html#cb27-7" tabindex="-1"></a></span>
<span id="cb27-8"><a href="preprocesamiento-y-visualizacion.html#cb27-8" tabindex="-1"></a><span class="co"># Supongamos que tienes tu serie de tiempo &#39;serie_ts&#39;</span></span>
<span id="cb27-9"><a href="preprocesamiento-y-visualizacion.html#cb27-9" tabindex="-1"></a><span class="co"># Aplicar cpt.mean para detectar cambios en la media</span></span>
<span id="cb27-10"><a href="preprocesamiento-y-visualizacion.html#cb27-10" tabindex="-1"></a>punto_cambio <span class="ot">&lt;-</span> <span class="fu">cpt.mean</span>(serie_ts)</span>
<span id="cb27-11"><a href="preprocesamiento-y-visualizacion.html#cb27-11" tabindex="-1"></a></span>
<span id="cb27-12"><a href="preprocesamiento-y-visualizacion.html#cb27-12" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb27-13"><a href="preprocesamiento-y-visualizacion.html#cb27-13" tabindex="-1"></a><span class="fu">summary</span>(punto_cambio)</span></code></pre></div>
<pre><code>## Created Using changepoint version 2.2.4 
## Changepoint type      : Change in mean 
## Method of analysis    : AMOC 
## Test Statistic  : Normal 
## Type of penalty       : MBIC with value, 19.4263 
## Minimum Segment Length : 1 
## Maximum no. of cpts   : 1 
## Changepoint Locations : 456</code></pre>
<p>segun los resultados obtenidos, se detectó <strong>un punto de cambio</strong> en la serie de tiempo.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Changepoint type</strong>: Define el tipo de cambio detectado. En este caso, es un <strong>cambio en la media</strong> de la serie (<code>Change in mean</code>), lo que implica que la función <code>cpt.mean</code> buscó variaciones significativas en el nivel promedio de los datos.</p></li>
<li><p><strong>Method of analysis: AMOC</strong>: El método <code>AMOC</code> (At Most One Change) implica que el análisis se ha limitado a identificar solo un posible cambio en la serie de tiempo.</p></li>
<li><p><strong>Test Statistic: Normal</strong>: La estadística de prueba utilizada para detectar el cambio es el test de normalidad, adecuado para datos que siguen una distribución normal.</p></li>
<li><p><strong>Type of penalty: MBIC with value, 19.4263</strong>: La penalización aplicada es la <code>MBIC</code> (Modified Bayesian Information Criterion), que ayuda a determinar la ubicación del cambio sin sobreajustar el modelo. El valor específico de esta penalización fue 19.4263, lo cual afecta el número de cambios detectados al favorecer soluciones con menos cambios.</p></li>
<li><p><strong>Minimum Segment Length: 1</strong>: Indica que la longitud mínima de un segmento entre los puntos de cambio es 1. Es decir, el análisis considera que el cambio puede ocurrir incluso en segmentos de un solo punto.</p></li>
<li><p><strong>Maximum no. of cpts: 1</strong>: Se limitó el número máximo de puntos de cambio a 1, lo cual es consistente con el método <code>AMOC</code> usado en el análisis.</p></li>
<li><p><strong>Changepoint Locations: 456</strong>: El único punto de cambio detectado se encuentra en la posición 456 de la serie de tiempo. Esto significa que se encontró un cambio significativo en la media en esa posición específica de la serie.</p></li>
</ol>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="preprocesamiento-y-visualizacion.html#cb29-1" tabindex="-1"></a><span class="co"># Graficar la serie de tiempo con los puntos de cambio</span></span>
<span id="cb29-2"><a href="preprocesamiento-y-visualizacion.html#cb29-2" tabindex="-1"></a><span class="fu">plot</span>(punto_cambio, <span class="at">main =</span> <span class="st">&quot;Puntos de Cambio en la Media&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
<div id="gráfica-acf-y-pacf-de-los-residuos" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Gráfica ACF y PACF de los residuos<a href="preprocesamiento-y-visualizacion.html#gráfica-acf-y-pacf-de-los-residuos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="preprocesamiento-y-visualizacion.html#cb30-1" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">residuals</span>(modelo_arima))</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="preprocesamiento-y-visualizacion.html#cb31-1" tabindex="-1"></a><span class="fu">pacf</span>(<span class="fu">residuals</span>(modelo_arima))</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-31-2.png" width="672" /></p>
</div>
<div id="prueba-de-ljung-box" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Prueba de Ljung-Box<a href="preprocesamiento-y-visualizacion.html#prueba-de-ljung-box" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="preprocesamiento-y-visualizacion.html#cb32-1" tabindex="-1"></a><span class="fu">Box.test</span>(<span class="fu">residuals</span>(modelo_arima), <span class="at">lag =</span> <span class="dv">10</span>, <span class="at">type =</span> <span class="st">&quot;Ljung-Box&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Box-Ljung test
## 
## data:  residuals(modelo_arima)
## X-squared = 329.69, df = 10, p-value &lt; 2.2e-16</code></pre>
<p>La prueba de Ljung-Box evalúa si los residuos del modelo ARIMA están autocorrelacionados. Esto es importante porque, idealmente, los residuos deberían comportarse como ruido blanco (es decir, sin patrones de autocorrelación) para indicar que el modelo ha capturado adecuadamente la estructura de la serie de tiempo. En esta prueba:</p>
<ul>
<li><strong>Hipótesis nula (H0)</strong>: No hay autocorrelación en los residuos, es decir, los residuos son ruido blanco.</li>
<li><strong>Hipótesis alternativa (H1)</strong>: Existe autocorrelación en los residuos.</li>
</ul>
<div id="interpretación-de-los-resultados" class="section level3 hasAnchor" number="3.9.1">
<h3><span class="header-section-number">3.9.1</span> Interpretación de los Resultados<a href="preprocesamiento-y-visualizacion.html#interpretación-de-los-resultados" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>Valor de X-squared</strong>: El estadístico de prueba <code>X-squared</code> es 329.69. Este valor indica cuánta autocorrelación existe entre los residuos en función del número de retardos especificado (en este caso, 10 retardos).</li>
<li><strong>Grados de libertad (df)</strong>: En este caso, son 10, lo cual corresponde al número de retardos que seleccionaste para el test.</li>
<li><strong>p-value</strong>: El valor p es menor que <span class="math inline">\(2.2 \times 10^{-16}\)</span>, lo cual es extremadamente bajo.</li>
</ul>
</div>
<div id="conclusión" class="section level3 hasAnchor" number="3.9.2">
<h3><span class="header-section-number">3.9.2</span> Conclusión<a href="preprocesamiento-y-visualizacion.html#conclusión" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dado que el valor p es mucho menor que el nivel de significancia típico (0.05), rechazamos la hipótesis nula. Esto sugiere que <strong>existe autocorrelación significativa en los residuos</strong> del modelo ARIMA. Esto indica que el modelo no ha capturado completamente los patrones en la serie de tiempo, por lo que podría necesitar ajustes adicionales en los valores de <code>p</code>, <code>d</code>, y <code>q</code> o en su parametrización general.</p>
<p>Para mejorar el modelo, considera:
1. Reexaminar el orden del modelo (ajustar <code>p</code>, <code>d</code>, <code>q</code>).
2. Probar otros modelos ARIMA, como un SARIMA si hay componentes estacionales.
3. Verificar si la serie requiere transformaciones adicionales.</p>
</div>
</div>
<div id="normalidad-de-los-residuos" class="section level2 hasAnchor" number="3.10">
<h2><span class="header-section-number">3.10</span> Normalidad de los residuos<a href="preprocesamiento-y-visualizacion.html#normalidad-de-los-residuos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="preprocesamiento-y-visualizacion.html#cb34-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(modelo_arima))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(modelo_arima)
## W = 0.95135, p-value = 8.511e-14</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="preprocesamiento-y-visualizacion.html#cb36-1" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">residuals</span>(modelo_arima), <span class="at">main =</span> <span class="st">&quot;Histograma de Residuos&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Residuos&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="gráfico-q-q-quantile-quantile" class="section level2 hasAnchor" number="3.11">
<h2><span class="header-section-number">3.11</span> Gráfico Q-Q (Quantile-Quantile)<a href="preprocesamiento-y-visualizacion.html#gráfico-q-q-quantile-quantile" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="preprocesamiento-y-visualizacion.html#cb37-1" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(modelo_arima))</span>
<span id="cb37-2"><a href="preprocesamiento-y-visualizacion.html#cb37-2" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(modelo_arima), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="Remesas-en-dolares_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>Dado el valor p tan bajo (inferior a un nivel de significancia típico de 0.05), rechazamos la hipótesis nula. Esto significa que los residuos del modelo no se distribuyen normalmente.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="descripción-de-las-series-de-tiempo.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/3_Preprocesamiento.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Remesas en dolares.pdf", "Remesas en dolares.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
